# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.10

# Mod Properties
mod_version=1.21
maven_group=com.reddit.user.koppeh.flamingo
archives_base_name=Flamingo

# Dependencies
fabric_version=0.115.1+1.21.1
